name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up
      run: |
        docker build -t uint:base -f Dockerfile.base .
        docker run -v "$(pwd):/home/uint/dotfiles" -w "/home/uint/dotfiles" --rm uint:base bash ./setup.sh
  Script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up with script
      run: |
        ./docker-base-ext.sh
