name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up
      run: |
        ./docker.sh
